import {json,text,name,currentUser,saveImage} from "../_common.js";
async function profile(env,username){const u=await env.DB.prepare("SELECT username,display_name AS displayName,bio,avatar,created_at AS createdAt FROM users WHERE username=?1").bind(username).first();if(!u)return null;const [followers,following]=await Promise.all([env.DB.prepare("SELECT follower FROM follows WHERE following=?1 ORDER BY created_at").bind(username).all(),env.DB.prepare("SELECT following FROM follows WHERE follower=?1 ORDER BY created_at").bind(username).all()]);return {...u,createdAt:Number(u.createdAt),followers:followers.results.map(x=>x.follower),following:following.results.map(x=>x.following)};}
async function directory(env,mode){
 const users=(await env.DB.prepare("SELECT username,display_name AS displayName,bio,avatar,created_at AS createdAt FROM users").all()).results;
 const out=[];
 for(const u of users){const f=await env.DB.prepare("SELECT COUNT(*) c FROM follows WHERE following=?1").bind(u.username).first();const fg=await env.DB.prepare("SELECT COUNT(*) c FROM follows WHERE follower=?1").bind(u.username).first();const p=await env.DB.prepare("SELECT COUNT(*) c FROM posts WHERE username=?1").bind(u.username).first();const l=await env.DB.prepare("SELECT COUNT(*) c FROM likes l JOIN posts p ON p.id=l.post_id WHERE p.username=?1").bind(u.username).first();const c=await env.DB.prepare("SELECT COUNT(*) c FROM comments c JOIN posts p ON p.id=c.post_id WHERE p.username=?1").bind(u.username).first();out.push({...u,createdAt:Number(u.createdAt),followers:[],following:[],followersCount:Number(f.c),followingCount:Number(fg.c),posts:Number(p.c),likes:Number(l.c),comments:Number(c.c)});}
 if(mode==="popular")out.sort((a,b)=>(b.followersCount*5+b.likes*2+b.comments*3+b.posts)-(a.followersCount*5+a.likes*2+a.comments*3+a.posts));else out.sort((a,b)=>b.createdAt-a.createdAt);return out.slice(0,40);
}
async function userPosts(env,username){const rows=(await env.DB.prepare("SELECT id,username,text,image,created_at AS createdAt FROM posts WHERE username=?1 ORDER BY created_at DESC LIMIT 50").bind(username).all()).results;for(const p of rows){const l=await env.DB.prepare("SELECT username FROM likes WHERE post_id=?1").bind(p.id).all();const c=await env.DB.prepare("SELECT id,username,display_name AS displayName,avatar,text,created_at AS createdAt FROM comments WHERE post_id=?1 ORDER BY created_at").bind(p.id).all();p.likes=l.results.map(x=>x.username);p.comments=c.results.map(x=>({...x,createdAt:Number(x.createdAt)}));p.createdAt=Number(p.createdAt)}return rows;}
export async function onRequestGet({request,env}){try{const url=new URL(request.url),mode=(url.searchParams.get("mode")||"").toLowerCase();if(mode==="popular"||mode==="explore")return json({users:await directory(env,mode)});if(mode==="stats"){const x=await env.DB.prepare("SELECT COUNT(*) c FROM users").first();return json({userCount:Number(x.c)})}const q=(url.searchParams.get("username")||"").trim().toLowerCase();if(!q)return json({error:"Kullanıcı adı gerekli."},400);const p=await profile(env,q);if(!p)return json({error:"Kullanıcı bulunamadı."},404);const me=await currentUser(env,request);return json({profile:p,posts:await userPosts(env,p.username),me:me?.username||null});}catch(e){return json({error:"Sunucu hatası."},500)}}
export async function onRequestPost({request,env}){try{const me=await currentUser(env,request);if(!me)return json({error:"Bu işlem için giriş yapmalısın."},401);const b=await request.json(),action=b.action;
 if(action==="update"){const displayName=name(b.displayName),bio=text(b.bio).slice(0,160);if(displayName.length<2)return json({error:"Görünen adın en az 2 karakter olsun."},400);let avatar=me.avatar||"";if(b.avatar!==undefined&&b.avatar!==avatar){avatar=await saveImage(env,b.avatar,"avatars",900*1024)}await env.DB.prepare("UPDATE users SET display_name=?1,bio=?2,avatar=?3 WHERE username=?4").bind(displayName,bio,avatar,me.username).run();return json({ok:true,profile:await profile(env,me.username)});}
 if(action==="follow"){const target=String(b.username||"").toLowerCase();if(!target||target===me.username)return json({error:"Kendini takip edemezsin."},400);if(!await env.DB.prepare("SELECT username FROM users WHERE username=?1").bind(target).first())return json({error:"Kullanıcı bulunamadı."},404);const old=await env.DB.prepare("SELECT 1 FROM follows WHERE follower=?1 AND following=?2").bind(me.username,target).first();if(old)await env.DB.prepare("DELETE FROM follows WHERE follower=?1 AND following=?2").bind(me.username,target).run();else await env.DB.prepare("INSERT INTO follows(follower,following,created_at) VALUES(?,?,?)").bind(me.username,target,Date.now()).run();return json({ok:true,following:!old,profile:await profile(env,target)});}
 if(action==="search"){const q=text(b.query).toLowerCase().slice(0,30);const r=await env.DB.prepare("SELECT u.username,u.display_name AS displayName,u.avatar,(SELECT COUNT(*) FROM follows f WHERE f.following=u.username) followers FROM users u WHERE lower(u.username) LIKE ?1 OR lower(u.display_name) LIKE ?1 ORDER BY followers DESC LIMIT 20").bind(`%${q}%`).all();return json({users:r.results});}
 return json({error:"Geçersiz işlem."},400);}catch(e){console.error(e);return json({error:e.message||"Sunucu hatası."},500)}}
